apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  template:
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_KEYCLOAK
              value: quay.io/keycloak/keycloak:22.0
          image: quay.io/keycloak/keycloak-operator:22.0
          name: keycloak-operator